version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,lambda
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    networks:
      - bank_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - bank_network

  mockserver:
    image: mockserver/mockserver
    ports:
      - "1080:1080"
    volumes:
      - ./init-mockserver.sh:/init-mockserver.sh
    command: "/init-mockserver.sh"
    networks:
      - bank_network

  aurora:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=bankdesafio
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - bank_network

  bankdesafio:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      aurora:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://aurora:3306/bankdesafio?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=secret
      - MOCKSERVER_URL=http://mockserver:1080
      - AWS_S3_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    networks:
      - bank_network

networks:
  bank_network:
    driver: bridge
